const resObj = [
  {
    id: "res001",
    name: "KFC",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    rating: 4.4,
    deliveryTime: "30-35 mins",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Fast Food", "Chicken"],
    location: "Koramangala",
    city: "Bangalore",
    description: "Delicious fried chicken, burgers and fast food.",
  },

  {
    id: "res002",
    name: "Pizza Hut",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
    rating: 4.3,
    deliveryTime: "25-30 mins",
    costForTwo: "₹350 for two",
    cuisines: ["Pizza", "Italian", "Fast Food"],
    location: "Indiranagar",
    city: "Bangalore",
    description: "Freshly baked pizzas with delicious toppings.",
  },

  {
    id: "res003",
    name: "Burger King",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    rating: 3.9,
    deliveryTime: "20-25 mins",
    costForTwo: "₹300 for two",
    cuisines: ["Burgers", "American", "Fast Food"],
    location: "HSR Layout",
    city: "Bangalore",
    description: "Flame-grilled burgers and crispy sides.",
  },

  {
    id: "res004",
    name: "Domino's Pizza",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
    rating: 3.0,
    deliveryTime: "25-30 mins", 
    costForTwo: "₹400 for two",
    cuisines: ["Pizza", "Italian", "Beverages"],
    location: "BTM Layout",
    city: "Bangalore",
    description: "Hot and fresh pizzas delivered to your doorstep.",
  },

  {
    id: "res005",
    name: "Subway",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569",
    rating: 4.1,
    deliveryTime: "20-25 mins",
    costForTwo: "₹350 for two",
    cuisines: ["Healthy Food", "Sandwiches", "Salads"],
    location: "Marathahalli",
    city: "Bangalore",
    description: "Fresh sandwiches, salads and healthy meals.",
  },

  {
    id: "res006",
    name: "McDonald's",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    rating: 4.3,
    deliveryTime: "20-25 mins",
    costForTwo: "₹300 for two",
    cuisines: ["Burgers", "Fast Food", "Beverages"],
    location: "Whitefield",
    city: "Bangalore",
    description: "Burgers, fries, beverages and more.",
  },
];

export default resObj;